# -*- coding: utf-8 -*-
"""MBBQ12023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jLhWoHUCsTLkJxLPTx5QgIScmN6PDu0m
"""

import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import folium_static

# Load the GeoJSON file
@st.cache
def load_data():
    return gpd.read_file("Malaysia_MBB_Q1_2023.geojson")

df = load_data()

# Select specific columns for further analysis
df = df[["quadkey", "avg_d_mbps", "avg_u_mbps", "avg_lat_ms", "tests", "devices", "geometry"]]

# Create a Streamlit app
def main():
    # Set page title
    st.title("Malaysia Mobile Broadband Analysis")

    # Create a Folium map
    m = folium.Map(location=[4.1093195, 109.45547499999998], tiles='openstreetmap', zoom_start=6)

    # Filter the data for average download speed <= 2.5 Mbps
    d = df[df.avg_d_mbps <= 2.5].set_index("quadkey")

    # Create a choropleth map using Folium
    choropleth = folium.Choropleth(
        geo_data=d.geometry._geo_interface_,
        data=d.avg_d_mbps,
        legend_name="Average Download Speed",
        fill_color="RdPu",
        opacity=1.5,
        highlight=True,
        key_on="feature.id"
    ).add_to(m)

    # Display the map using Streamlit
    folium_static(m)

if _name_ == "_main_":
    main()