# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzjyI2asWcWBM9sKbRVaQtoMUYGjRzWQ
"""

!pip install streamlit

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("2NwbRUZ1K5KQjGGABjBnRff6og5_7WCaz1MwW7fNKG3GRZPAL")

!nohup streamlit run Streamlit_app.py --server.port 80 &
url = ngrok.connect(port='80')
print(url)

!pip install streamlit-folium

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium

APP_TITLE = 'Fraud and Identity Theft Report'
APP_SUB_TITLE = 'Source: Federal Trade Commission'

def display_time_filters(df):
    year_list = list(df['Year'].unique())
    year_list.sort()
    year = st.sidebar.selectbox('Year', year_list, len(year_list)-1)
    quarter = st.sidebar.radio('Quarter', [1, 2, 3, 4])
    st.header(f'{year} Q{quarter}')
    return year, quarter

def display_state_filter(df, state_name):
    state_list = [''] + list(df['State Name'].unique())
    state_list.sort()
    state_index = state_list.index(state_name) if state_name and state_name in state_list else 0
    return st.sidebar.selectbox('State', state_list, state_index)

def display_report_type_filter():
    return st.sidebar.radio('Report Type', ['Fraud', 'Other'])

def display_map(df, year, quarter):
    df = df[(df['Year'] == year) & (df['Quarter'] == quarter)]

map = folium.Map(location=[38, -96.5], zoom_start=4, scrollWheelZoom=False, tiles='CartoDB positron')
st_map = st_folium(map)

def main():
  st.set_page_config(APP_TITLE)
  st.title(APP_TITLE)
  st.caption(APP_SUB_TITLE)



#Load_Data

df_fraud_conti = pd.read_csv('AxS-Continental_Full Data_data.csv')















